language: node_js
node_js:
  - 10.11
matrix:
    include:
      - os: linux
        script: xvfb-run npm test
      - os: osx
        script: npm test
      - os: windows
        script: npm test
dist: xenial
notifications:
    email: false
